# Jekyll Resume Theme

# Site settings
title: Abhishek Bamotra
email: abamotra1707@gmail.com
description: Resume, projects, internships, blog of Abhishek Bamotra.
baseurl: ""
url: ""
name: Abhishek Bamotra
job: mechatronics undergraduate
location: Thapar University, India
languages: Arduino, Robotics and CAD
twitter_username: abhibamotra
github_username:  abhishekbamotra
email_address: abamotra1707@gmail.com

# Build settings
markdown: kramdown
